# Generated by Django 2.0.3 on 2018-03-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20180328_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='authorPlaceholder', max_length=100),
        ),
    ]
