# Generated by Django 2.0.3 on 2018-03-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='large_img',
            field=models.CharField(default='largeImgPlaceholder', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='small_img',
            field=models.CharField(default='smallImgPlaceholder', max_length=200),
        ),
    ]
