# Generated by Django 2.0.3 on 2018-03-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='descriptionPlaceholder', max_length=2000),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='isbnPlaceholder', max_length=15, primary_key=True, serialize=False, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='bookstore.Author'),
        ),
    ]
