# Generated by Django 2.0.3 on 2018-03-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
