# Generated by Django 2.0.3 on 2018-03-30 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_book_for_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_date', models.DateTimeField(verbose_name='date placed')),
                ('total_amount', models.FloatField(default=0.0)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.BookInstance')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book'),
        ),
    ]
